M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date сб, 08-кві-2023 18:09:59 +0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-08T18:09:59+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X-4.6Y4.0
X-4.6Y0.2
X-0.2Y4.0
X-0.2Y0.2
T0
M30
